### ISSUE TITLE
Occasionally, a broken pipe causes flow build to fail 

### ISSUE THREAD

**Issue by anissen** [snowkit/flow#29]
Sometimes (maybe once out of every ten) build attempts fail in the following manner:

```
$ flow run
flow / 1.0.0-alpha.1
flow / target is mac ( arch 64 )

flow / project - searching project root /Users/nissen/code/snowkit/test
flow / project - using project file /Users/nissen/code/snowkit/test/project.flow
flow / build - test 0.0.1 for mac
flow / build - running haxe ...
/usr/lib/haxe/std/neko/_std/Sys.hx:25: characters 10-28 : Broken pipe
/usr/lib/haxe/lib/haxelib_client/3,1,0-rc,4/tools/haxelib/Main.hx:1244: characters 2-21 : Called from
/usr/lib/haxe/lib/haxelib_client/3,1,0-rc,4/tools/haxelib/Main.hx:300: characters 5-25 : Called from
/usr/lib/haxe/lib/haxelib_client/3,1,0-rc,4/tools/haxelib/Main.hx:1248: characters 2-22 : Called from
--macro:1: character 0 : Called from
Aborted
```

This error has been observed building both from the command line and from Sublime Text using the flow-plugin.

Following the stack trace, `haxelib` seems to fails in `getRepository()` in `haxelib/Main.hx`. Strangely, inserting `trace` in that function causes the following error:

```
$ flow run
/usr/lib/haxe/lib/haxelib_client/3,1,0-rc,4/tools/haxelib/Main.hx:695: inserted dummy trace
flow / 1.0.0-alpha.1
flow / target is mac ( arch 64 )

flow / project - searching project root /Users/nissen/code/snowkit/test
flow / project - using project file /Users/nissen/code/snowkit/test/project.flow
flow / build - test 0.0.1 for mac
flow / build - running haxe ...
Error: Could not process argument /usr/lib/haxe/lib/hxcpp/3,1,39/
Class name must start with uppercase character
```

To me, this seems to indicate that the `haxelib` output is used by `flow/hxcpp` and there might be some race condition causing this to fail non-deterministically. This is only speculations though.

Any ideas?

**Comment by Geemili** [comment]
This happens to me as well. The error I recieve is:
```
flow / 1.0.0-alpha.1
flow / target is linux ( arch 64 )

flow / project - searching project root /home/geemili/art/games/movers
flow / project - using project file /home/geemili/art/games/movers/project.flow
flow / build - Movers 0.0.1 for linux
flow / no icon convert just yet for linux
flow / build - running haxe ...
/usr/lib/haxe/std/neko/_std/Sys.hx:25: characters 10-28 : Broken pipe
/usr/lib/haxe/extra/haxelib_src/src/tools/haxelib/Main.hx:1371: characters 2-21 : Called from
/usr/lib/haxe/extra/haxelib_src/src/tools/haxelib/Main.hx:311: characters 5-25 : Called from
/usr/lib/haxe/extra/haxelib_src/src/tools/haxelib/Main.hx:1375: characters 2-22 : Called from
--macro:1: character 0 : Called from
Aborted
```

**Comment by kewp** [comment]
I get a similar error when there is a space in my path

**Comment by underscorediscovery** [comment]
thanks @kewp for the comment, do you mean PATH as in ENV path? or just the project path?

**Comment by kewp** [comment]
I mean the project path

**Comment by anissen** [comment]
This issue appears to have been solved with Haxe 3.2.0 RC2 and the version of `haxelib` that's bundled with it. I'll close this issue.

---

**If you're having this problem** and...

* are using a Haxe version earlier than 3.2.0 RC2
  => try upgrading to the latest version of Haxe

* are using Haxe 3.2.0 RC2 or later
  => please re-open this issue

**Comment by joekinley** [comment]
Gotta reopen, sorry: 

```
flow run linux
flow / 1.0.0-alpha.1
flow / target is linux ( arch 64 )
flow / haxe version 3.2.0 (git build development @ 8880048)

flow / build - aymuraykilla 0.0.1 for linux
flow / no icon convert just yet for linux
flow / build - running haxe ...
/home/joekinley/.hvm/versions/haxe/dev/std/neko/_std/Sys.hx:25: characters 10-28 : Broken pipe
/home/joekinley/.hvm/versions/haxelib/dev/tools/haxelib/Main.hx:249: characters 2-23 : Called from
/home/joekinley/.hvm/versions/haxelib/dev/tools/haxelib/Main.hx:488: characters 5-25 : Called from
/home/joekinley/.hvm/versions/haxelib/dev/tools/haxelib/Main.hx:1649: characters 2-22 : Called from
?:1: characters 1048575-8796094070782 : Called from
Aborted
Fatal error: exception Sys_error("Broken pipe")
```

**Comment by joekinley** [comment]
This one gets really annoying. Anything to help with this? Can I help, or is there some workaround?

**Comment by DjPale** [comment]
This happens to me consistently when building native under RPi2. Web builds work fine.

`
Linux rpi2 3.18.11-v7+ #781 SMP PREEMPT Tue Apr 21 18:07:59 BST 2015 armv7l GNU/Linux
Haxe Library Manager 3.2.0-rc.3 - (c)2006-2015 Haxe Foundation
Haxe Compiler 3.2.0 - (C)2005-2015 Haxe Foundation
`
When flow is running the step `haxe bin/linux.build/build.hxml`

From what I can see this is from the haxe compiler - it catches it from the OCAML "layer" (I did some searches on Google).

I've seen this behavior "sporadic" - and guess this has something to do with underlying timeouts or similar from the OS. I guess that the reason that I'm seeing this every time on the RPi2 target is because of the low speed(?).
