### ISSUE TITLE
FLOW: error on haxelib.js:54

### ISSUE THREAD

**Issue by oxitech239** [snowkit/flow#65]
Despite multiple attempts at getting the latest flow from repo.
-----
haxelib run flow run
flow / 1.0.0-alpha.2 (node.js v0.12.7)
flow / target is linux ( arch 64 )
flow / haxe version 3.4.2

/home/user/.haxelib/flow/git/src/flow/util/haxelib.js:54
                throw new HaxelibError(reason);
                      ^
HaxelibError: > haxelib config cannot be called. Is haxe/haxelib installed?

**Comment by underscorediscovery** [comment]
it seems it is having trouble finding `haxelib` in your PATH. You can try `haxelib run flow run --log 3` to get more info on what it's doing.

**Comment by oxitech239** [comment]
Thanks for the quick response :)

haxelib run flow run --log 3
flow / 1.0.0-alpha.2 (node.js v0.12.7)
flow / current platform is linux
flow / target is linux ( arch 64 )
flow / process util - running : haxe -version
flow / haxe version 3.4.2
flow / process util - running : haxelib config

/home/user/.haxelib/flow/git/src/flow/util/haxelib.js:54
                throw new HaxelibError(reason);
                      ^
HaxelibError: > haxelib config cannot be called. Is haxe/haxelib installed?

**Comment by oxitech239** [comment]
i read somewhere it is because there is a static path for haxelib in haxelib.js but i could not find it right away

**Comment by underscorediscovery** [comment]
It's [here](https://github.com/snowkit/flow/blob/master/src/flow/util/haxelib.js#L50) I think you mean? The question is why can it see [haxe](https://github.com/snowkit/flow/blob/master/src/flow/util/haxelib.js#L22) command but not haxelib?

**Comment by oxitech239** [comment]
i'm not sure, from the CLI haxelib does not need any path, it is known.
I'm using ATOM and have set the static path for both haxe and haxelib to no avail

**Comment by underscorediscovery** [comment]
So it doesn't even work if you hardcode some path there (like `/usr/local/lib/haxe/haxelib`)? I'm not sure how atom would be messing with the path, hmm!

**Comment by oxitech239** [comment]
if you mean hardcode the path in haxelib.js ? I've set it to /usr/local/bin/haxelib to no avail

**Comment by underscorediscovery** [comment]
that is really strange, but it only fails when run via atom is what I was wondering?

**Comment by oxitech239** [comment]
depends on how one looks at it, if i run build in atom it fails with the same error as on the CLI, but it does fail stating haxelib cannot be found, hence it must be in the code

**Comment by underscorediscovery** [comment]
> i'm not sure, from the CLI haxelib does not need any path, it is known.

I am trying to figure out what is happening that's all :)
- When you run on CLI, you get an error as well? 
- When you run with a hardcoded path is _also_ fails from CLI?

**Comment by oxitech239** [comment]
Anything fails when i run flow with some commands such as build, config, setup

**Comment by oxitech239** [comment]
AH! weird, when i navigate to the path of my code, then run haxelib run flow it requests 

~/test $ haxelib run flow
Error: This is the first time you are runing haxelib. Please run `haxelib setup` first

**Comment by underscorediscovery** [comment]
aha, so it might just be that the message is consumed quietly somehow, causing the config command to fail, which is misinterpreted as not finding haxelib (i.e the error catch in flow is too broad)

**Comment by underscorediscovery** [comment]
I bet once you setup haxelib it should work again

**Comment by oxitech239** [comment]
well, eh, haxelib has been set-up already for the user folder
I assumed it needed be setup once and hence would work for all sub-folders, grmbl

**Comment by underscorediscovery** [comment]
it's a global setting I think? I've never needed to run haxelib setup repeatedly on the same machine?

**Comment by oxitech239** [comment]
`haxelib setup` shows a different path than the installed packages listed with `haxelib list` which are under ~/.haxelib/

**Comment by oxitech239** [comment]
the project.flow can be empty, right ?

**Comment by underscorediscovery** [comment]
no it requires a version and a name but it will tell you this. You can test against an empty snow sample perhaps?

**Comment by oxitech239** [comment]
fast stupid yet not so stupid approach would be to setup a new repo in my source dir, thus having all packages dedicated to this project

**Comment by oxitech239** [comment]
stuck ... even 'haxelib setup' does not work as expected, i just pressed enter, something broke i figure
---
haxelib setup
Please enter haxelib repository path with write access
Hit enter for default (/usr/lib/haxe/lib)
Path : 
Error: [file_open,/home/user/.haxelib]
--- 
i need sleep, good night, will update if a fix emerges

**Comment by oxitech239** [comment]
ah, just found this thread which does appears related https://github.com/HaxeFoundation/haxelib/issues/161

**Comment by oxitech239** [comment]
Yawn, created a symlink to /home/user/.haxelib/ in /home/user/test/

~/test $ haxelib list
actuate: [1.8.7]
castle: [1.5.0]
dbadmin: [1.1.0]
filesystemhelper: [1.0.0]
flow: 0.0.0 [git]
haxe-nme-vfs: [0.0.1]
haxeui: [1.8.21]
hscript: [2.0.7]
hxbit: [1.1.0]
kha: [16.1.2]
lime-samples: [4.0.1]
lime-tools: [1.5.7]
lime: 2.9.1 4.0.2 [4.0.3]
logshim: [0.0.4]
mongomod: [1.0.4]
nme: [5.7.1]
openfl: 3.6.1 [4.9.2]
snow: [git]
tink_cli: [0.2.1]
tink_core: 1.9.1 [1.11.0]
tink_csss: [0.1.0]
tink_http: [0.7.0]
tink_http_fetch: [0.2.0]
tink_io: [0.5.0]
tink_json: [0.5.0]
tink_lang: [0.5.0]
tink_macro: 0.13.3 [0.13.4]
tink_parse: [0.2.0]
tink_priority: [0.1.3]
tink_pure: [0.3.0]
tink_querystring: [0.3.0]
tink_state: [0.4.2]
tink_streams: [0.2.1]
tink_stringly: [0.1.0]
tink_syntaxhub: [0.3.6]
tink_tcp: [0.1.1]
tink_template: [0.3.2]
tink_typecrawler: [0.5.0]
tink_url: 0.3.0 [0.3.1]
tink_validation: [0.2.0]
tink_web: [0.0.0-alpha.0]
tink_xml: [0.2.0]

~/test $ haxelib run flow build

haxelib run flow build
flow / 1.0.0-alpha.2 (node.js v0.12.7)
flow / target is linux ( arch 64 )
flow / build only
flow / haxe version 3.4.2

/home/user/.haxelib/flow/git/src/flow/util/haxelib.js:54
                throw new HaxelibError(reason);
                      ^
HaxelibError: > haxelib config cannot be called. Is haxe/haxelib installed?

It is a bug for sure, though unclear if it is in haxelib or in haxelib.js (though these are unrelated)

**Comment by oxitech239** [comment]
haxelib setup
Please enter haxelib repository path with write access
Hit enter for default (/usr/lib/haxe/lib)
Path : ./.haxelib
Error: Can't use /home/user/.haxelib because it is reserved for config file

**Comment by underscorediscovery** [comment]
It seems that it just doesn't like that path? Say if you had `./haxe/lib/` instead of the fixed config path

**Comment by oxitech239** [comment]
it's just bizar, and also something reported earlier on github for haxelib, i'll have a look tomorrow, thanks for the feedback. Stuff like this shakes my confidence in chosing haxe/haxelib as my platform for development, substantially.

**Comment by underscorediscovery** [comment]
I'm sympathetic to your concerns, I get frustrated by this type of occasional situation too.

**Comment by oxitech239** [comment]
Assuming it was cause by using ~/.haxelib as repository path i did a `haxelib deleterepo` and start reinstalling into ~/code/haxelib/ which now works fine

**Comment by underscorediscovery** [comment]
glad it's working now

**Comment by oxitech239** [comment]
The struggle to work with flow snow is on :)
