### ISSUE TITLE
Full doc url throws a 404

### ISSUE THREAD

**Issue by oxitech239** [snowkit/flow#66]
http://snowkit.github.io/snow/guide/build-details.html#project says has full documentation here which ends up at target http://snowkit.org/flow/docs/project/ which throws a 404

i'm a bit lost in all this and there's no slack or irc live

**Comment by underscorediscovery** [comment]
The link is just outdated, it should point here : http://snowkit.github.io/flow/

The chat is http://snowkit.org/chat and it's linked on a few places.

**Comment by oxitech239** [comment]
Oops that, i kept looking over it
